In [13]:
from spiderstate.cat_at_origin import *
from spidercat.draw import draw_forest_on_graph
from spiderstate.utils import load_qecc

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [46]:
is_self_dual, H_x, H_z, L_x, L_z, d = load_qecc("144_12_12")
t = d // 2
# H_x = H_z

cost, row_M = row_optimize_matrix(H_z, t=t, max_basis_tries=1_000)

import pprint
pprint.pprint(cost)

np.uint64(4980)


In [47]:
circ = cat_at_origin(row_M, d, draw_solutions=False)

In [48]:
print(circ)
circ.diagram('timeline-svg')

R 0
RX 1 2
R 3 4
RX 5
R 6
RX 7 8
R 9 10
RX 11 12 13
R 14 15
RX 16 17 18 19 20
R 21 22 23 24
RX 25
R 26 27
RX 28 29 30 31 32 33 34
R 35 36 37
RX 38 39 40
R 41 42
RX 43
R 44
RX 45 46 47
R 48 49 50 51 52
RX 53 54 55 56
R 57 58 59
RX 60 61
R 62 63 64 65 66 67
RX 68 69 70
R 71 72 73 74
RX 75 76
R 77
RX 78
R 79
RX 80
R 81 82 83 84 85
RX 86
R 87 88
RX 89 90 91
R 92 93
RX 94
R 95 96
RX 97
R 98
RX 99 100
R 101 102
RX 103 104
R 105 106 107 108 109
RX 110 111 112
R 113
RX 114
R 115 116 117 118 119 120 121 122 123
RX 124 125
R 126 127 128 129
RX 130 131
R 132
RX 133
R 134
RX 135
R 136
RX 137
R 138
RX 139
R 140
RX 141 142 143 144
CX 144 0
RX 145
CX 145 0
R 146
CX 1 146
R 147
CX 1 147
R 148
CX 2 148
R 149
CX 2 149
RX 150
CX 150 3
RX 151
CX 151 3
RX 152
CX 152 4
RX 153
CX 153 4
R 154
CX 5 154
R 155
CX 5 155
RX 156
CX 156 6
RX 157
CX 157 6
R 158
CX 7 158
R 159
CX 7 159
R 160
CX 8 160
R 161
CX 8 161
RX 162
CX 162 9
RX 163
CX 163 9
RX 164
CX 164 10
RX 165
CX 165 10
R 166
CX 11 166
R 167
CX 11 167
R 168


In [50]:
circuit = circ.copy()
circuit.append("M", range(H_z.shape[1]))
samples = circuit.compile_sampler().sample(10)
meas_samples = samples[:, -H_z.shape[1]:]
print(meas_samples @ H_x.T % 2)
print(meas_samples @ L_x.T % 2)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [51]:
from spidercat.simulate import _layer_cnot_circuit

raw_cnots = [l for (name, l, _) in circ.flattened_operations() if name == "CX"]
cnots = [(ops[i], ops[i + 1]) for ops in raw_cnots for i in range(0, len(ops), 2)]
print("Num CX:", len(cnots))
print("Num Flags:", circ.num_qubits - H_z.shape[1])
print("Num qubits:", circ.num_qubits)
layered_cnots = _layer_cnot_circuit(cnots)
print("Depth:", len(layered_cnots))

Num CX: 5202
Num Flags: 1887
Num qubits: 2031
Depth: 115


In [43]:
print(np.sum(row_M, axis=0))
print(np.sum(row_M, axis=1))

[23  1 19  1  7  1 15 19  1  1  1 13  1 19  1  1  1  1  1  1  1  1 23  1
 17 25  1  1  1 13 23  1 17  7 19 27 13 17 15  1  1 19  1  1 21 19  1  1
  1  1  1 15  1 17 21 19  1 29 21 23  1  1 13  1 19  1  1  1 21 19 17  1
 19 21 17  1 17  1 19  1  1  1 21 19 17 19 25 19  1 19 17  1]
[ 8 24 18 22 18 22 18 18 22 24  8 24 22 22 22 20  8 28 26 20 22 20 26 20
 22 22 28 22 22  8 10 14 22 20 22 30 20 32 18 20 26 18 26 22 12]


In [44]:
print(np.sum(H_z, axis=0))
print(np.sum(H_z, axis=1))

[4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4 4 3 4 4
 4 4 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4
 3 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8
 8 8 8 8 8 8 8 8]


In [45]:
import pprint
for r in row_M:
    pprint.pprint(r, width=400)

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0], dtype=uint8)
array([1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0], dtype=uint8)
array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0], dtype=uint8)
array([0, 0, 1, 0, 1, 0, 

In [17]:
with open("64_8_8.stim", "w") as f:
    f.write(str(circ))

In [27]:
import stim

c = stim.Circuit("""
RX 0
R 1
CX 0 1
R 2
CX 0 2
R 3
CX 1 3
R 4
CX 2 4
R 5
CX 0 5
R 6
CX 2 6
R 7
CX 0 7
R 8
CX 2 8
R 12
CX 6 12
R 9
CX 7 9
R 10
CX 0 10
R 13
CX 7 13 0 12
M 12
R 14
CX 7 14
R 11
CX 0 11 0 14
M 14
R 15
CX 0 15 2 15
M 15
R 16
CX 2 16 1 16
M 16
CX 1 13
M 13
""")

with open("well_ordered_cat_state.svg", "w") as f:
    f.write(str(c.diagram('timeline-svg')))